### ISSUE TITLE
Update phantomenv

### ISSUE THREAD

**Issue by DanielWright** [boxen/puppet-phantomjs#16]
The version of phantomenv installed by this module contains out-of-date download links for the phantomjs binaries. Not ideal.

This has been fixed (see https://github.com/wfarr/phantomenv/commit/000b5f39513a01196f5f6980fb5f9b689611976f), but the commits haven't been included in a tagged release, so I can't submit a quickie PR to update [this line](https://github.com/boxen/puppet-phantomjs/blob/master/manifests/params.pp#L19) accordingly. However, once https://github.com/wfarr/phantomenv/issues/5 is addressed, I will!

In the meantime, I will leave this GHI to aid my porous memory.

**Comment by brodock** [comment]
:+1:

**Comment by wfarr** [comment]
> I'm waiting @wfarr moev phantomenv to boxen organization to help him with the issues. As soon he do it we will do another release.

This repo has been moved.

**Comment by DanielWright** [comment]
Exciting. :+1:

**Comment by mislav** [comment]
This was fixed in aaab3f8e7d368ea7f1ff44279e011576ea81fb1d
